### ISSUE TITLE
Does not follow html $ref

### ISSUE THREAD

**Issue by bsvedin** [armand-janssen/openapi-transformer#55]
It will not follow a $ref that points to an html resource. Error is (company info removed)
 UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open './https://artifactory.cloud.mycompany.com/artifactory/maven/common-<version>.yaml'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at loadYamlFile (C:\Users\212708371\AppData\Roaming\npm\node_modules\openapi-transformer\src\index.js:59:21)
    at C:\Users\212708371\AppData\Roaming\npm\node_modules\openapi-transformer\src\index.js:78:47
    at Array.forEach (<anonymous>)
    at Object.loadYamlFile (C:\Users\212708371\AppData\Roaming\npm\node_modules\openapi-transformer\src\index.js:77:23)
    at C:\Users\212708371\AppData\Roaming\npm\node_modules\openapi-transformer\src\cli.js:30:53
    at Object.<anonymous> (C:\Users\212708371\AppData\Roaming\npm\node_modules\openapi-transformer\src\cli.js:56:5)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:36168) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:36168) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by armand-janssen** [comment]
Can you provide a OpenApi sample so I can reproduce this? What is the content of the html file?
if the ref starts with 'http' it should not hit the code mentioned in the error.

Thanks!
